# Site settings
title: MeadSteve's Dev Blog
email: meadsteve@gmail.com
author: Steve Brazier
description: "Rambling thoughts, ideas and other stuff from MeadSteve"
baseurl: ""
animated: false
show_related_posts: false
unpublished: true
future: true


collections:
  knowledgebase:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 40
sass:
  compressed: true

plugins:
- pygmentize
- jekyll-paginate
- kramdown
- addressable
- jekyll-watch
