# Site settings
title: MeadSteve's Dev Blog
email: meadsteve@gmail.com
author: Steve Brazier
description: "Rambling thoughts, ideas and other stuff from MeadSteve"
baseurl: ""
url: "https://blog.meadsteve.dev"
animated: false
show_related_posts: false
unpublished: true
future: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 80
sass:
  compressed: true

plugins:
- pygmentize
- jekyll-paginate
- kramdown
- addressable
- jekyll-watch
